// SPDX-License-Identifier: AGPL-3.0
// Feel free to change the license, but this is what we use

pragma solidity ^0.8.12;
pragma experimental ABIEncoderV2;

// These are the core Yearn libraries
import { BaseStrategy, StrategyParams } from "@yearnvaults/contracts/BaseStrategy.sol";

import { Address } from "@openzeppelin/contracts/utils/Address.sol";
import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { Market } from "../src/interfaces/Market.sol";
import { RewardsController } from "../src/interfaces/rewards.sol";
import { IVelodromeRouter } from "../src/interfaces/IVelodromeRouter.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";
import "@openzeppelin/contracts/utils/math/Math.sol";

// Import interfaces for many popular DeFi projects, or add your own!
//import "./interfaces/<protocol>/<Interface>.sol";

contract Strategy is BaseStrategy {
    using SafeERC20 for IERC20;
    using Address for address;
    using SafeMath for uint256;

    IERC20 public constant op =
        IERC20(0x4200000000000000000000000000000000000042);

    Market public constant exactly =
        Market(0x81C9A7B55A4df39A9B7B5F781ec0e53539694873);
    RewardsController public constant rewardsController =
        RewardsController(0xBd1ba78A3976cAB420A9203E6ef14D18C2B2E031);
    IVelodromeRouter public constant router =
        IVelodromeRouter(0x9c12939390052919aF3155f41Bf4160Fd3666A6f);

    // solhint-disable-next-line no-empty-blocks
    constructor(address _vault) BaseStrategy(_vault) {
        // You can set these parameters on deployment to whatever you want
        maxReportDelay = 6300;
        //        profitFactor = 100;
        // debtThreshold = 0;
        op.approve(address(router), type(uint256).max);
        want.approve(address(exactly), type(uint256).max);
    }

    // ******** OVERRIDE THESE METHODS FROM BASE CONTRACT ************

    function name() external view override returns (string memory) {
        // Add your own name here, suggestion e.g. "StrategyCreamYFI"
        return "Strategy<ProtocolName><TokenType>";
    }

    function shareToAssets() public view returns (uint256) {
        uint256 exa_bal = exactly.balanceOf(address(this));
        return exactly.convertToAssets(exa_bal);
    }

    function wantBalance() public view returns (uint256) {
        return want.balanceOf(address(this));
    }

    function estimatedTotalAssets() public view override returns (uint256) {
        // TODO: Build a more accurate estimate using the value of all positions in terms of `want`
        return wantBalance().add(shareToAssets());
    }

    function prepareReturn(
        uint256 _debtOutstanding
    )
        internal
        override
        returns (uint256 _profit, uint256 _loss, uint256 _debtPayment)
    // solhint-disable-next-line no-empty-blocks
    {
        // TODO: Do stuff here to free up any returns back into `want`
        // NOTE: Return `_profit` which is value generated by all positions, priced in `want`
        // NOTE: Should try to free up at least `_debtOutstanding` of underlying position
        if (rewardsController.allClaimable(address(this), address(op)) > 0) {
            rewardsController.claimAll(address(this));
            _sellRewards();
        }
        uint256 stakedBal = exactly.balanceOf(address(this));
        if (_debtOutstanding > 0) {
            if (stakedBal > 0) {
                exactly.redeem(
                    Math.min(stakedBal, _debtOutstanding),
                    address(this),
                    address(this)
                );
            }
            uint256 withdrawnBal = wantBalance();
            _debtPayment = Math.min(stakedBal, _debtOutstanding);
        }
        uint256 assets = estimatedTotalAssets();
        uint256 debt = vault.strategies(address(this)).totalDebt;

        if (assets > debt) {
            _profit = assets.sub(debt);
            uint256 _wantBal = wantBalance();
            if (_profit.add(_debtPayment) > _wantBal) {
                liquidateAllPositions();
            }
        } else {
            _loss = debt.sub(assets);
        }
    }

    // solhint-disable-next-line no-empty-blocks
    function adjustPosition(uint256 _debtOutstanding) internal override {
        // TODO: Do something to invest excess `want` tokens (from the Vault) into your positions
        // NOTE: Try to adjust positions so that `_debtOutstanding` can be freed up on *next* harvest (not immediately)
        uint256 _wantBal = wantBalance();
        if (_wantBal > 0) {
            exactly.deposit(_wantBal, address(this));
        }
    }

    function liquidatePosition(
        uint256 _amountNeeded
    ) internal override returns (uint256 _liquidatedAmount, uint256 _loss) {
        // TODO: Do stuff here to free up to `_amountNeeded` from all positions back into `want`
        // NOTE: Maintain invariant `want.balanceOf(this) >= _liquidatedAmount`
        // NOTE: Maintain invariant `_liquidatedAmount + _loss <= _amountNeeded`

        uint256 _wantBal = want.balanceOf(address(this));
        if (_amountNeeded > _wantBal) {
            uint256 _stakedBalance = shareToAssets();
            if (_stakedBalance > 0) {
                exactly.withdraw(
                    Math.min(_stakedBalance, _amountNeeded.sub(_wantBal)),
                    address(this),
                    address(this)
                );
            }
            uint256 _withdrawnBalance = wantBalance();
            _liquidatedAmount = Math.min(_amountNeeded, _withdrawnBalance);
            _loss = _amountNeeded.sub(_liquidatedAmount);
        } else {
            return (_amountNeeded, 0);
        }
    }

    function liquidateAllPositions() internal override returns (uint256) {
        // TODO: Liquidate all positions and return the amount freed.
        uint256 _exactlyBal = exactly.balanceOf(address(this));
        if (_exactlyBal > 0) {
            exactly.redeem(_exactlyBal, address(this), address(this));
        }
        return wantBalance();
    }

    // NOTE: Can override `tendTrigger` and `harvestTrigger` if necessary
    // solhint-disable-next-line no-empty-blocks
    function prepareMigration(address _newStrategy) internal override {
        // TODO: Transfer any non-`want` tokens to the new strategy
        // NOTE: `migrate` will automatically forward all `want` in this strategy to the new one

        uint256 _exactlyBal = exactly.balanceOf(address(this));
        if (_exactlyBal > 0) {
            exactly.redeem(_exactlyBal, address(this), address(this));
        }
    }

    function _sellRewards() internal {
        uint op_bal = op.balanceOf(address(this));
        router.swapExactTokensForTokensSimple(
            op_bal,
            0,
            address(op),
            address(want),
            false,
            address(this),
            block.timestamp
        );
    }

    // Override this to add all tokens/tokenized positions this contract manages
    // on a *persistent* basis (e.g. not just for swapping back to want ephemerally)
    // NOTE: Do *not* include `want`, already included in `sweep` below
    //
    // Example:
    //
    //    function protectedTokens() internal override view returns (address[] memory) {
    //      address[] memory protected = new address[](3);
    //      protected[0] = tokenA;
    //      protected[1] = tokenB;
    //      protected[2] = tokenC;
    //      return protected;
    //    }
    function protectedTokens()
        internal
        view
        override
        returns (address[] memory)
    // solhint-disable-next-line no-empty-blocks
    {

    }

    /**
     * @notice
     *  Provide an accurate conversion from `_amtInWei` (denominated in wei)
     *  to `want` (using the native decimal characteristics of `want`).
     * @dev
     *  Care must be taken when working with decimals to assure that the conversion
     *  is compatible. As an example:
     *
     *      given 1e17 wei (0.1 ETH) as input, and want is USDC (6 decimals),
     *      with USDC/ETH = 1800, this should give back 1800000000 (180 USDC)
     *
     * @param _amtInWei The amount (in wei/1e-18 ETH) to convert to `want`
     * @return The amount in `want` of `_amtInEth` converted to `want`
     **/
    function ethToWant(
        uint256 _amtInWei
    ) public view virtual override returns (uint256) {
        // TODO create an accurate price oracle
        return _amtInWei;
    }
}
